#!/bin/bash
#
# WAM CMIS (providence) deployment script
#
# This script currently only manages code update deployments, and does not handle
# initial setup or updates involving a database migration.
#

#halt on any errors
set -e
# halt on undefined variables
set -u

# Defaults
defaultClonePath=/data/github/providence
defaultTargetParentPath=/data/cmis/collectiveaccess/providence
defaultTagPrefix=wamuseum_
defaultTagName=$(date +%Y%m%d%H%M%S)
defaultSymlinkName=current
defaultService=php5-fpm

# Initial values
clonePath=$defaultClonePath
targetParentPath=$defaultTargetParentPath
tagPrefix=$defaultTagPrefix
tagName=$defaultTagName
symlinkName=$defaultSymlinkName
service=$defaultService

skipPull=false
skipDeploy=false
skipLink=false
skipRestartService=false
skipPushTag=false

# Parse parameters
declare -a errors
showHelp=false
for opt in "$@"; do
	case "$opt" in
		-c=*|--clone-path=*)
			clonePath="${opt#*=}"
		;;
		-p=*|--target-parent-path=*)
			targetParentPath="${opt#*=}"
		;;
		-t=*|--tag-name=*)
			tagName="${opt#*=}"
		;;
		-x=*|--tag-prefix=*)
			tagPrefix="${opt#*=}"
		;;
		-s=*|--symlink-name=*)
			symlinkName="${opt#*=}"
		;;
		-r=*|--restart-service=*)
			service="${opt#*=}"
		;;
		-P|--skip-pull)
			skipPull=true
		;;
		-D|--skip-deploy)
			skipDeploy=true
		;;
		-L|--skip-link)
			skipLink=true
		;;
		-R|--skip-restart-service)
			skipRestartService=true
		;;
		-T|--skip-push-tag)
			skipPushTag=true
		;;
		-h|--help)
			showHelp=true
		;;
		*=*)
			errors[${#errors[@]}]="Unrecognised option: ${opt%=*} with value: ${opt#*=}"
		;;
		*)
			errors[${#errors[@]}]="Unrecognised option: $opt with no value"
		;;
	esac
done

# Sanity check options
if [[ "$clonePath" = "" ]]; then
	errors[${#errors[@]}]="Empty clone path specified"
fi
if [[ "$targetParentPath" = "" ]]; then
	errors[${#errors[@]}]="Empty target parent path specified"
fi
if [[ "$tagName" = "" ]]; then
	errors[${#errors[@]}]="Empty tag name specified, use -T to skip tagging"
fi
if [[ "$symlinkName" = "" ]]; then
	errors[${#errors[@]}]="Empty symlink name specified, use -L to skip linking"
fi
if [[ "$service" = "" ]]; then
	errors[${#errors[@]}]="Empty service name specified, use -R to skip restarting service"
elif [ ! -e "/etc/init.d/$service" ]; then
	errors[${#errors[@]}]="Non-existent service name $service specified, use -R to skip restarting service"
fi

# Composite variables
targetPath="$targetParentPath/$tagName"
targetSymlinkPath="$targetParentPath/$symlinkName"
tagFullName="$tagPrefix$tagName"

# Path checking
if [ ! -d $clonePath ]; then
    errors[${#errors[@]}]="Cloned repository path does not exist: $clonePath"
fi
if [ ! -d $targetParentPath ]; then
    errors[${#errors[@]}]="Target parent path does not exist: $targetParentPath"
fi
if [ -d $targetPath ]; then
    errors[${#errors[@]}]="Tag directory already exists: $tagName"
fi

# Show errors and/or usage
if [[ ${#errors[@]} > 0 || $showHelp = true ]]; then
	if [[ $showHelp != true ]]; then
		echo "ERRORS:"
		for error in "${errors[@]}"; do
			echo "    $error"
		done
		echo ""
	fi

	cat << ENDHELP
USAGE:
    ${0##*/} [OPTIONS]

OPTIONS:
    -c, --clone-path=PATH         Path to the local git clone
                                  ($defaultClonePath)
    -p, --target-parent-path=PATH Path containing deployment subdirs
                                  ($defaultTargetParentPath)
    -t, --tag-name=NAME           Name of the tag, this is used for the local
                                  subdir name and (optionally) to create a tag
                                  in the repo (defaults to current date)
    -x, --tag-prefix=PREFIX       Prefix to use before the tag name, this is
                                  used for tag name only ($defaultTagPrefix)
    -s, --symlink-name=NAME       Name of the symlink to create; this should
                                  match server configuration ($defaultSymlinkName)
    -r, --restart-service=SERVICE Name of service to restart ($defaultService)
    -P, --skip-pull               Don't pull latest changes from upstream
    -D, --skip-deploy             Don't copy changes from clone to target
    -L, --skip-link               Don't create a new link in target directory
    -R, --skip-restart-server     Don't restart any service
    -T, --skip-push-tag           Don't create and push a tag
    -h, --help                    Show this help text and quit

ENDHELP
	exit
fi

# Process steps...
if [ $skipPull = false ]; then
	echo "Pulling latest changes from remote git repository..."
	pushd "$clonePath" >/dev/null
	git checkout master
	git pull origin master
	popd >/dev/null
	echo "Done pulling latest changes from remote git repository"
fi

if [ $skipDeploy = false ]; then
	echo "Deploying latest changes to staging directory..."
	if [ -e "$targetSymlinkPath" ]; then
		cp -R "$targetSymlinkPath/" "$targetPath"
	fi
	rsync -a --exclude=".git*" --delete --delete-excluded "$clonePath" "$targetPath"
	echo "Done deploying latest changes to staging directory"
fi

if [ $skipLink = false ]; then
	echo "Linking production to staging directory..."
	if [[ -h $targetSymlinkPath ]]; then  # -h = "exists and is a symbolic link"
		rm $targetSymlinkPath
	fi
	ln -s $targetPath $targetSymlinkPath
	echo "Done linking production to staging directory"
fi

if [ $skipRestartService = false ]; then
	echo "Restarting service $service..."
	sudo service $service restart
	echo "Done restarting service $service"
fi

if [ $skipPushTag = false ]; then
	echo "Adding a tag for the deployed version..."
	pushd "$clonePath" >/dev/null
	git tag -a "$tagFullName" -m "Tagging $tagFullName [from deployment script, deploy-wamcmis]"
	git push origin "$tagFullName"
	popd >/dev/null
	echo "Done adding a tag for the deployed version"
fi

# $SECONDS is a magic, per-script variable given by bash
echo "DEPLOYMENT COMPLETED IN $SECONDS SECONDS"
