#!/bin/bash
#
# WAM CMIS (providence) installation profile export script
#
# This script exports the current installation profile from a CollectiveAccess installation and then strips the large taxonomy out of it.
#
echo "$0: installation profile exporter"

# Halt on any errors
set -e

# Halt on undefined variables
set -u

# Constants
profileFileName="wamcmis.xml"
profileName='Western Australian Museum CMIS'
profileUrl='http://wamwpcmis.da.wa.gov.au'
profileDescription='Western Australian Museum Collection Managment Information System'
xslt="`dirname $0`/stripTaxonomy.xslt"

# Make sure we have a CA installation available
`dirname $0`/checkCollectiveAccess

# Determine the export path
if [ $# -gt 0 ]; then
	currentProfilePath="$1/$profileFileName"
else
	currentProfilePath="$COLLECTIVEACCESS_HOME/install/profiles/xml/$profileFileName"
fi

# Make sure xsltproc is installed in order to process the profile and remove unwanted elements
if ! `which xsltproc > /dev/null` ; then
	echo -e "You sould have xsltproc installed. You can install it using\n\tsudo apt-get install xsltproc"
	exit 1
fi
echo -e "\txsltproc installed at `which xsltproc`"
echo "Now exporting profile"

# Export the profile
caUtils export-profile -u "$profileUrl" -d "$profileDescription" -n "$profileName" -o "$currentProfilePath.export"
xsltproc "$xslt" "$currentProfilePath.export" > "$currentProfilePath.stripped"
mv "$currentProfilePath.stripped" "$currentProfilePath"
rm "$currentProfilePath.export"

